### ISSUE TITLE
Implemt All API requests possible to MCLOGS for easy plugin log uploads!

### ISSUE THREAD

**Issue by wolflord212312** [p0t4t0sandwich/TaterUtils#10]

**Comment by wolflord212312** [comment]
https://api.mclo.gs/

**Comment by wolflord212312** [comment]
This is just  HTTP/HTTPS Requests Not hard to add compared to others

**Comment by p0t4t0sandwich** [comment]
Shooting this over to [TaterUtils](https://github.com/p0t4t0sandwich/TaterUtils), as it's a tad out of scope for TaterLib's current setup (TaterLib isn't set up for multiple modules atm). Can always swing the feature back in if it fits later on.

**Comment by p0t4t0sandwich** [comment]
Turns out they got a nifty lib: https://github.com/aternosorg/mclogs-java
Close to being finished a simple implementation

**Comment by p0t4t0sandwich** [comment]
Got an easy API written up, just need to get commands figured at some point

**Comment by p0t4t0sandwich** [comment]
This was implemented upstream in TaterLib. Can't choose a specific log to upload, but it's close enough
